# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('manager', models.CharField(max_length=64)),
            ],
        ),
    ]
